export const QUERY_CHANGE = 'QUERY_CHANGE';

export const REPOS_FETCH_FAIL = 'REPOS_FETCH_FAIL';
export const REPOS_FETCH_START = 'REPOS_FETCH_START';
export const REPOS_FETCH_SUCCESS = 'REPOS_FETCH_SUCCESS';

export const USER_FETCH_START = 'USER_FETCH_START';
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
export const USER_FETCH_FAIL = 'USER_FETCH_FAIL';